CREATE TABLE BRANCH
(BRANCH_NUM int NOT NULL PRIMARY KEY,
BRANCH_NAME varchar (256),
BRANCH_LOCATION varchar (256),
NUM_EMPLOYEES int NOT NULL);

CREATE TABLE PUBLISHER
(PUBLISHER_CODE varchar (100) NOT NULL PRIMARY KEY,
PUBLISHER_NAME varchar (256) NOT NULL,
CITY varchar (256));

CREATE TABLE BOOK
(BOOK_CODE varchar (256) NOT NULL PRIMARY KEY,
TITLE varchar (256) NOT NULL,
PUBLISHER_CODE varchar (100) NOT NULL,
BOOK_GENRE varchar (256) NOT NULL,
PRICE decimal (18,2) NOT NULL,
PAPERBACK varchar (90),
FOREIGN KEY (PUBLISHER_CODE) REFERENCES PUBLISHER (PUBLISHER_CODE));

CREATE TABLE AUTHOR
(AUTHOR_NUM int NOT NULL PRIMARY KEY,
AUTHOR_LAST_NAME varchar (256) NOT NULL,
AUTHOR_FIRST_NAME varchar (256) NOT NULL);

CREATE TABLE WROTE
(BOOK_CODE varchar (256) NOT NULL,
AUTHOR_NUM int NOT NULL,
BOOK_SEQUENCE int,
FOREIGN KEY (BOOK_CODE) REFERENCES BOOK (BOOK_CODE),
FOREIGN KEY (AUTHOR_NUM) REFERENCES AUTHOR (AUTHOR_NUM));

CREATE TABLE INVENTORY
(BOOK_CODE varchar (256) NOT NULL,
BRANCH_NUM int NOT NULL,
ON_HAND int NOT NULL,
FOREIGN KEY (BOOK_CODE) REFERENCES BOOK (BOOK_CODE),
FOREIGN KEY (BRANCH_NUM) REFERENCES BRANCH (BRANCH_NUM));

CREATE TABLE SALES
(SALES_NUM bigint NOT NULL PRIMARY KEY,
SALES_DATE date NOT NULL,
BOOK_CODE varchar (256) NOT NULL,
NUMBER_ORDERED int,
PRICE decimal (18,2) NOT NULL,
BRANCH_NUM int NOT NULL,
FOREIGN KEY (BOOK_CODE) REFERENCES BOOK (BOOK_CODE),
FOREIGN KEY (BRANCH_NUM) REFERENCES BRANCH (BRANCH_NUM));

CREATE TABLE BRANCH_EMPLOYEES
(EMP_ID int NOT NULL PRIMARY KEY,
EMP_LNAME varchar (256),
EMP_FNAME varchar (256),
EMP_JOB_CODE varchar (256),
EMP_JOB_STATUS varchar (256),
EMP_HOURLY_WAGE decimal (18,2),
BRANCH_NUM int NOT NULL,
FOREIGN KEY (BRANCH_NUM) REFERENCES BRANCH (BRANCH_NUM));
